"""
Slack chatbot Lambda handler.
"""

import os
import logging
import json
from slackclient import SlackClient

# grab the Bot OAuth token from the environment and create slack client instance
BOT_TOKEN = os.getenv("BOT_TOKEN", "DEFAULT_TOKEN")
SLACK_CLIENT = SlackClient(BOT_TOKEN)

# set logger level
logger = logging.getLogger()
logger.setLevel(logging.INFO)


def lambda_handler(event, context):
    """
    Handle an incoming HTTP request from subscribed events
    """
    data = json.loads(event["body"])
    logger.info(data)
    # logger.info(context)
    if "challenge" in data:
        logger.info("Request URL verification message received, return challenge data")
        return {
            "statusCode": 200,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({"challenge": data["challenge"]}),
        }

    # get the Slack event data
    slack_event = data["event"]

    # we need to discriminate between events generated by the users,
    # which we want to process and handle, and those generated by the bot
    if "bot_id" in slack_event:
        logger.info("Ignore bot event and acknowledge the receipt of message")
        return {
            "statusCode": 200,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({"ok": True}),
        }
    else:
        # get data for the event, including channel_id, message text
        text = slack_event["text"]
        channel_id = slack_event["channel"]

        # send response back to Slack API
        r = SLACK_CLIENT.api_call("chat.postMessage", channel=channel_id, text=text)

        if r["ok"] is True:
            logger.info("Message has been successfully posted")
            return {
                "statusCode": 200,
                "headers": {"Content-Type": "application/json"},
                "body": json.dumps({"ok": True}),
            }
        else:
            logger.error("Error: post message failed")
            return {
                "statusCode": 500,
                "headers": {"Content-Type": "text/plain"},
                "body": "Message posted but no confirmation from Slack server",
            }
